
version: 2

models:
  - name: dim_video
    description: "Dimension for Video"

  - name: dim_video_hashtag
    description: "Dimension for Video hashtags"

  - name: dim_caption
    description: "Dimension for Caption"

  - name: dim_caption_language
    description: "Dimension for Caption language"

  - name: dim_thumbnail
    description: "Dimension for Thumbnail content"

  - name: dim_thumbnail_size
    description: "Dimension for Thumbnail size"

  - name: dim_channel
    description: "Dimension for Channel"
  # - name: my_first_dbt_model
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       tests:
  #         - unique
  #         - not_null

